namespace G_Sharp;

# region Tipos
public enum SyntaxKind
{
    // tokens
    WhitespaceToken,
    NumberToken,
    PlusToken,
    MinusToken,
    MultToken,
    DivisionToken,
    ModToken,
    OpenParenthesisToken,
    ClosedParenthesisToken,
    ErrorToken,
    EndOfFileToken,
    SemicolonToken,
    IdentifierToken,
    GreaterToken,
    LessToken,
    EqualToken,
    GreaterOrEqualToken,
    LessOrEqualToken,
    AssignmentToken,
    DifferentToken, 
    StringToken,
    SeparatorToken,
    CircleToken,
    PointToken,
    ArcToken,
    LineToken,
    SegmentToken,
    RayToken,
    MeasureToken,
    ClosedCurlyBracketToken,
    OpenCurlyBracketToken,
    CommentToken,
    MathToken,
    ColorToken,
    SuspenseToken,
    UndefinedToken,

    // Expressions
    LiteralExpression,
    BinaryExpression,
    ParenthesizedExpression,
    UnaryExpression,
    ConstantExpression,
    ConstantAssignmentExpression,   
    FunctionExpression,
    AssignmentFunctionExpression,
    LetInExpression,
    ConditionalExpression,
    SequenceExpression,
    DrawExpression,
    VoidExpression,

    // Keywords
    AndKeyword,
    OrKeyword,
    NotKeyword,
    LetKeyword,
    InKeyword,
    IfKeyword,
    ElseKeyword,
    ThenKeyword,
    ColorKeyword,
    GeometryKeyword,
    DrawKeyword,
    RestoreKeyword,
    SequenceKeyword,
    ImportKeyword
}

#endregion
